//
// Created by Oleg Morozenkov on 20.06.17.
//

#ifndef RECAST_SCALINGGENERATABLECHUNKEDTEMPERATUREWORLDINJECTOR_H
#define RECAST_SCALINGGENERATABLECHUNKEDTEMPERATUREWORLDINJECTOR_H


class ScalingGeneratableChunkedTemperatureWorldInjector {

};


#endif //RECAST_SCALINGGENERATABLECHUNKEDTEMPERATUREWORLDINJECTOR_H
