//
// Created by Oleg Morozenkov on 19.06.17.
//

#ifndef RECAST_THREADEDCHUNKEDTEMPERATUREWORLDUPDATERANNOTATIONS_H
#define RECAST_THREADEDCHUNKEDTEMPERATUREWORLDUPDATERANNOTATIONS_H

namespace ThreadedChunkedTemperatureWorldUpdaterAnnotations {
    struct ChunkUpdaterFactoryFn {};
}

#endif //RECAST_THREADEDCHUNKEDTEMPERATUREWORLDUPDATERANNOTATIONS_H
